// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

export class AvailableOutbound {
    "tag": string;
    "type": string;
    "kind": string;

    /** Creates a new AvailableOutbound instance. */
    constructor($$source: Partial<AvailableOutbound> = {}) {
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AvailableOutbound instance from a string or object.
     */
    static createFrom($$source: any = {}): AvailableOutbound {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AvailableOutbound($$parsedSource as Partial<AvailableOutbound>);
    }
}

export class BuildInfo {
    "appVersion": string;
    "singBoxVersion": string;
    "buildTime": string;
    "buildNumber": string;
    "commitSha": string;

    /** Creates a new BuildInfo instance. */
    constructor($$source: Partial<BuildInfo> = {}) {
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }
        if (!("singBoxVersion" in $$source)) {
            this["singBoxVersion"] = "";
        }
        if (!("buildTime" in $$source)) {
            this["buildTime"] = "";
        }
        if (!("buildNumber" in $$source)) {
            this["buildNumber"] = "";
        }
        if (!("commitSha" in $$source)) {
            this["commitSha"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuildInfo($$parsedSource as Partial<BuildInfo>);
    }
}

export class BuiltinTemplate {
    "id": string;
    "path"?: string;
    "name": string;
    "description": string;
    "policies": Policy[];
    "ruleSets": RuleSet[];
    "dnsServers": DNSServer[];
    "dnsPolicies": DNSPolicy[];
    "settings": Settings;
    "settingsRecord"?: { [_ in string]?: string };

    /** Creates a new BuiltinTemplate instance. */
    constructor($$source: Partial<BuiltinTemplate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("policies" in $$source)) {
            this["policies"] = [];
        }
        if (!("ruleSets" in $$source)) {
            this["ruleSets"] = [];
        }
        if (!("dnsServers" in $$source)) {
            this["dnsServers"] = [];
        }
        if (!("dnsPolicies" in $$source)) {
            this["dnsPolicies"] = [];
        }
        if (!("settings" in $$source)) {
            this["settings"] = (new Settings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuiltinTemplate instance from a string or object.
     */
    static createFrom($$source: any = {}): BuiltinTemplate {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType8;
        const $$createField9_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("policies" in $$parsedSource) {
            $$parsedSource["policies"] = $$createField4_0($$parsedSource["policies"]);
        }
        if ("ruleSets" in $$parsedSource) {
            $$parsedSource["ruleSets"] = $$createField5_0($$parsedSource["ruleSets"]);
        }
        if ("dnsServers" in $$parsedSource) {
            $$parsedSource["dnsServers"] = $$createField6_0($$parsedSource["dnsServers"]);
        }
        if ("dnsPolicies" in $$parsedSource) {
            $$parsedSource["dnsPolicies"] = $$createField7_0($$parsedSource["dnsPolicies"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField8_0($$parsedSource["settings"]);
        }
        if ("settingsRecord" in $$parsedSource) {
            $$parsedSource["settingsRecord"] = $$createField9_0($$parsedSource["settingsRecord"]);
        }
        return new BuiltinTemplate($$parsedSource as Partial<BuiltinTemplate>);
    }
}

export class ClashProbe {
    "available": boolean;
    "url": string;
    "version": string;
    "message": string;

    /** Creates a new ClashProbe instance. */
    constructor($$source: Partial<ClashProbe> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClashProbe instance from a string or object.
     */
    static createFrom($$source: any = {}): ClashProbe {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClashProbe($$parsedSource as Partial<ClashProbe>);
    }
}

export class ClearOperationResult {
    "success": boolean;
    "error"?: string;

    /** Creates a new ClearOperationResult instance. */
    constructor($$source: Partial<ClearOperationResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClearOperationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ClearOperationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClearOperationResult($$parsedSource as Partial<ClearOperationResult>);
    }
}

export class ConfigImportResult {
    "policies": number;
    "ruleSets": number;
    "replaced": boolean;

    /** Creates a new ConfigImportResult instance. */
    constructor($$source: Partial<ConfigImportResult> = {}) {
        if (!("policies" in $$source)) {
            this["policies"] = 0;
        }
        if (!("ruleSets" in $$source)) {
            this["ruleSets"] = 0;
        }
        if (!("replaced" in $$source)) {
            this["replaced"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigImportResult($$parsedSource as Partial<ConfigImportResult>);
    }
}

export class ConfigOperationResult {
    "ok": boolean;
    "path"?: string;
    "error"?: string;

    /** Creates a new ConfigOperationResult instance. */
    constructor($$source: Partial<ConfigOperationResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigOperationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigOperationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigOperationResult($$parsedSource as Partial<ConfigOperationResult>);
    }
}

export class ConfigPreview {
    "path": string;
    "content": string;
    "changed": boolean;
    "warnings": string[];

    /** Creates a new ConfigPreview instance. */
    constructor($$source: Partial<ConfigPreview> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("changed" in $$source)) {
            this["changed"] = false;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigPreview {
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField3_0($$parsedSource["warnings"]);
        }
        return new ConfigPreview($$parsedSource as Partial<ConfigPreview>);
    }
}

export class Connection {
    "id": string;
    "host": string;
    "network": string;
    "outbound": string;
    "upload": number;
    "download": number;
    "age": string;

    /** Creates a new Connection instance. */
    constructor($$source: Partial<Connection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("network" in $$source)) {
            this["network"] = "";
        }
        if (!("outbound" in $$source)) {
            this["outbound"] = "";
        }
        if (!("upload" in $$source)) {
            this["upload"] = 0;
        }
        if (!("download" in $$source)) {
            this["download"] = 0;
        }
        if (!("age" in $$source)) {
            this["age"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     */
    static createFrom($$source: any = {}): Connection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection($$parsedSource as Partial<Connection>);
    }
}

export class CoreCheckResult {
    "ok": boolean;
    "path": string;
    "message": string;

    /** Creates a new CoreCheckResult instance. */
    constructor($$source: Partial<CoreCheckResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoreCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CoreCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoreCheckResult($$parsedSource as Partial<CoreCheckResult>);
    }
}

export class CoreServiceStatus {
    "platform": string;
    "supported": boolean;
    "socketAvailable": boolean;
    "binaryInstalled": boolean;
    "serviceLoaded": boolean;
    "running": boolean;
    "pid"?: number;
    "version"?: string;
    "needsUpgrade"?: boolean;
    "singboxRunning"?: boolean;
    "singboxPid"?: number;
    "singboxStartTime"?: number;
    "servicePath"?: string;
    "message"?: string;

    /** Creates a new CoreServiceStatus instance. */
    constructor($$source: Partial<CoreServiceStatus> = {}) {
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("socketAvailable" in $$source)) {
            this["socketAvailable"] = false;
        }
        if (!("binaryInstalled" in $$source)) {
            this["binaryInstalled"] = false;
        }
        if (!("serviceLoaded" in $$source)) {
            this["serviceLoaded"] = false;
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoreServiceStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CoreServiceStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoreServiceStatus($$parsedSource as Partial<CoreServiceStatus>);
    }
}

export class CustomProxyGroup {
    "name": string;
    "type": string;
    "outbounds": string[];
    "order": number;

    /** Creates a new CustomProxyGroup instance. */
    constructor($$source: Partial<CustomProxyGroup> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("outbounds" in $$source)) {
            this["outbounds"] = [];
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomProxyGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): CustomProxyGroup {
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("outbounds" in $$parsedSource) {
            $$parsedSource["outbounds"] = $$createField2_0($$parsedSource["outbounds"]);
        }
        return new CustomProxyGroup($$parsedSource as Partial<CustomProxyGroup>);
    }
}

export class CustomProxyGroupOrder {
    "name": string;
    "order": number;

    /** Creates a new CustomProxyGroupOrder instance. */
    constructor($$source: Partial<CustomProxyGroupOrder> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomProxyGroupOrder instance from a string or object.
     */
    static createFrom($$source: any = {}): CustomProxyGroupOrder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CustomProxyGroupOrder($$parsedSource as Partial<CustomProxyGroupOrder>);
    }
}

export class DNSPolicy {
    "id": string;
    "type": string;
    "name": string;
    "domain": string;
    "domainSuffix": string[];
    "domainKeyword": string[];
    "ruleSet": string[];
    "queryType": string[];
    "network": string[];
    "server": string;
    "strategy": string;
    "raw_data"?: { [_ in string]?: any };
    "enabled": boolean;

    /** Creates a new DNSPolicy instance. */
    constructor($$source: Partial<DNSPolicy> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }
        if (!("domainSuffix" in $$source)) {
            this["domainSuffix"] = [];
        }
        if (!("domainKeyword" in $$source)) {
            this["domainKeyword"] = [];
        }
        if (!("ruleSet" in $$source)) {
            this["ruleSet"] = [];
        }
        if (!("queryType" in $$source)) {
            this["queryType"] = [];
        }
        if (!("network" in $$source)) {
            this["network"] = [];
        }
        if (!("server" in $$source)) {
            this["server"] = "";
        }
        if (!("strategy" in $$source)) {
            this["strategy"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): DNSPolicy {
        const $$createField4_0 = $$createType10;
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType10;
        const $$createField7_0 = $$createType10;
        const $$createField8_0 = $$createType10;
        const $$createField11_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("domainSuffix" in $$parsedSource) {
            $$parsedSource["domainSuffix"] = $$createField4_0($$parsedSource["domainSuffix"]);
        }
        if ("domainKeyword" in $$parsedSource) {
            $$parsedSource["domainKeyword"] = $$createField5_0($$parsedSource["domainKeyword"]);
        }
        if ("ruleSet" in $$parsedSource) {
            $$parsedSource["ruleSet"] = $$createField6_0($$parsedSource["ruleSet"]);
        }
        if ("queryType" in $$parsedSource) {
            $$parsedSource["queryType"] = $$createField7_0($$parsedSource["queryType"]);
        }
        if ("network" in $$parsedSource) {
            $$parsedSource["network"] = $$createField8_0($$parsedSource["network"]);
        }
        if ("raw_data" in $$parsedSource) {
            $$parsedSource["raw_data"] = $$createField11_0($$parsedSource["raw_data"]);
        }
        return new DNSPolicy($$parsedSource as Partial<DNSPolicy>);
    }
}

export class DNSRuntimeStatus {
    "success": boolean;
    "data"?: DNSRuntimeStatusData;
    "error"?: string;

    /** Creates a new DNSRuntimeStatus instance. */
    constructor($$source: Partial<DNSRuntimeStatus> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSRuntimeStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DNSRuntimeStatus {
        const $$createField1_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new DNSRuntimeStatus($$parsedSource as Partial<DNSRuntimeStatus>);
    }
}

export class DNSRuntimeStatusData {
    "running": boolean;
    "address"?: string;
    "cert_path"?: string;
    "status"?: string;

    /** Creates a new DNSRuntimeStatusData instance. */
    constructor($$source: Partial<DNSRuntimeStatusData> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSRuntimeStatusData instance from a string or object.
     */
    static createFrom($$source: any = {}): DNSRuntimeStatusData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DNSRuntimeStatusData($$parsedSource as Partial<DNSRuntimeStatusData>);
    }
}

export class DNSServer {
    "id": string;
    "name": string;
    "tag": string;
    "type": string;
    "address": string;
    "server": string;
    "server_port"?: number;
    "path"?: string;
    "addressResolver": string;
    "addressStrategy": string;
    "detour": string;
    "strategy": string;
    "prefer_go"?: boolean | null;
    "domain_resolver"?: string;
    "raw_data"?: { [_ in string]?: any };
    "upstreams"?: string;
    "use_proxy"?: boolean;
    "bootstrap_addrs"?: string;
    "fallback_addrs"?: string;
    "enabled": boolean;

    /** Creates a new DNSServer instance. */
    constructor($$source: Partial<DNSServer> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("server" in $$source)) {
            this["server"] = "";
        }
        if (!("addressResolver" in $$source)) {
            this["addressResolver"] = "";
        }
        if (!("addressStrategy" in $$source)) {
            this["addressStrategy"] = "";
        }
        if (!("detour" in $$source)) {
            this["detour"] = "";
        }
        if (!("strategy" in $$source)) {
            this["strategy"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSServer instance from a string or object.
     */
    static createFrom($$source: any = {}): DNSServer {
        const $$createField14_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("raw_data" in $$parsedSource) {
            $$parsedSource["raw_data"] = $$createField14_0($$parsedSource["raw_data"]);
        }
        return new DNSServer($$parsedSource as Partial<DNSServer>);
    }
}

export class DNSServerRef {
    "source": string;
    "index": number;
    "name": string;

    /** Creates a new DNSServerRef instance. */
    constructor($$source: Partial<DNSServerRef> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSServerRef instance from a string or object.
     */
    static createFrom($$source: any = {}): DNSServerRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DNSServerRef($$parsedSource as Partial<DNSServerRef>);
    }
}

export class DashboardState {
    "coreRunning": boolean;
    "uptime": string;
    "profiles": number;
    "nodes": number;
    "policies": number;
    "dnsRules": number;
    "ruleSets": number;
    "upload": number;
    "download": number;
    "activeNode": string;
    "health": ProbeItem[];

    /** Creates a new DashboardState instance. */
    constructor($$source: Partial<DashboardState> = {}) {
        if (!("coreRunning" in $$source)) {
            this["coreRunning"] = false;
        }
        if (!("uptime" in $$source)) {
            this["uptime"] = "";
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = 0;
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = 0;
        }
        if (!("policies" in $$source)) {
            this["policies"] = 0;
        }
        if (!("dnsRules" in $$source)) {
            this["dnsRules"] = 0;
        }
        if (!("ruleSets" in $$source)) {
            this["ruleSets"] = 0;
        }
        if (!("upload" in $$source)) {
            this["upload"] = 0;
        }
        if (!("download" in $$source)) {
            this["download"] = 0;
        }
        if (!("activeNode" in $$source)) {
            this["activeNode"] = "";
        }
        if (!("health" in $$source)) {
            this["health"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DashboardState instance from a string or object.
     */
    static createFrom($$source: any = {}): DashboardState {
        const $$createField10_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("health" in $$parsedSource) {
            $$parsedSource["health"] = $$createField10_0($$parsedSource["health"]);
        }
        return new DashboardState($$parsedSource as Partial<DashboardState>);
    }
}

export class DatabaseStatus {
    "path": string;
    "backupDir": string;
    "schemaVersion": number;
    "currentVersion": number;
    "needsMigration": boolean;
    "profiles": number;
    "policies": number;
    "dnsServers": number;
    "dnsPolicies": number;
    "ruleSets": number;
    "preferences": number;
    "updatedAt": time$0.Time;

    /** Creates a new DatabaseStatus instance. */
    constructor($$source: Partial<DatabaseStatus> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("backupDir" in $$source)) {
            this["backupDir"] = "";
        }
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = 0;
        }
        if (!("needsMigration" in $$source)) {
            this["needsMigration"] = false;
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = 0;
        }
        if (!("policies" in $$source)) {
            this["policies"] = 0;
        }
        if (!("dnsServers" in $$source)) {
            this["dnsServers"] = 0;
        }
        if (!("dnsPolicies" in $$source)) {
            this["dnsPolicies"] = 0;
        }
        if (!("ruleSets" in $$source)) {
            this["ruleSets"] = 0;
        }
        if (!("preferences" in $$source)) {
            this["preferences"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DatabaseStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseStatus($$parsedSource as Partial<DatabaseStatus>);
    }
}

export class IPInfo {
    "ip": string;
    "country": string;
    "countryCode": string;

    /** Creates a new IPInfo instance. */
    constructor($$source: Partial<IPInfo> = {}) {
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("country" in $$source)) {
            this["country"] = "";
        }
        if (!("countryCode" in $$source)) {
            this["countryCode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): IPInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPInfo($$parsedSource as Partial<IPInfo>);
    }
}

export class InitialLogLineCount {
    "lineCount": number;

    /** Creates a new InitialLogLineCount instance. */
    constructor($$source: Partial<InitialLogLineCount> = {}) {
        if (!("lineCount" in $$source)) {
            this["lineCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InitialLogLineCount instance from a string or object.
     */
    static createFrom($$source: any = {}): InitialLogLineCount {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InitialLogLineCount($$parsedSource as Partial<InitialLogLineCount>);
    }
}

export class LauncherTaskResult {
    "success": boolean;
    "error"?: string;
    "needsRestart"?: boolean;

    /** Creates a new LauncherTaskResult instance. */
    constructor($$source: Partial<LauncherTaskResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LauncherTaskResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LauncherTaskResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LauncherTaskResult($$parsedSource as Partial<LauncherTaskResult>);
    }
}

export class LogEntry {
    "id": string;
    "level": string;
    "source": string;
    "message": string;
    "time": time$0.Time;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

export class LogInput {
    "level": string;
    "module": string;
    "message": string;

    /** Creates a new LogInput instance. */
    constructor($$source: Partial<LogInput> = {}) {
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("module" in $$source)) {
            this["module"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogInput instance from a string or object.
     */
    static createFrom($$source: any = {}): LogInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogInput($$parsedSource as Partial<LogInput>);
    }
}

export class LogReadOptions {
    "fromLine": number;
    "search": string;
    "maxResults": number;

    /** Creates a new LogReadOptions instance. */
    constructor($$source: Partial<LogReadOptions> = {}) {
        if (!("fromLine" in $$source)) {
            this["fromLine"] = 0;
        }
        if (!("search" in $$source)) {
            this["search"] = "";
        }
        if (!("maxResults" in $$source)) {
            this["maxResults"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogReadOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): LogReadOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogReadOptions($$parsedSource as Partial<LogReadOptions>);
    }
}

export class LogReadResult {
    "lines": string[];
    "totalLines": number;
    "isSearch": boolean;

    /** Creates a new LogReadResult instance. */
    constructor($$source: Partial<LogReadResult> = {}) {
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }
        if (!("totalLines" in $$source)) {
            this["totalLines"] = 0;
        }
        if (!("isSearch" in $$source)) {
            this["isSearch"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogReadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LogReadResult {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField0_0($$parsedSource["lines"]);
        }
        return new LogReadResult($$parsedSource as Partial<LogReadResult>);
    }
}

export class OrderItem {
    "id": string;
    "order": number;

    /** Creates a new OrderItem instance. */
    constructor($$source: Partial<OrderItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrderItem instance from a string or object.
     */
    static createFrom($$source: any = {}): OrderItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OrderItem($$parsedSource as Partial<OrderItem>);
    }
}

export class PlatformStatus {
    "os": string;
    "singBoxPath": string;
    "singBoxVersion": string;
    "systemProxy": boolean;
    "autoStart": boolean;
    "coreService": boolean;
    "tunReady": boolean;
    "dataDir": string;
    "generatedConfig": string;
    "platformMessage": string;
    "needsPrivilege": boolean;
    "supportedProxyApi": boolean;

    /** Creates a new PlatformStatus instance. */
    constructor($$source: Partial<PlatformStatus> = {}) {
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("singBoxPath" in $$source)) {
            this["singBoxPath"] = "";
        }
        if (!("singBoxVersion" in $$source)) {
            this["singBoxVersion"] = "";
        }
        if (!("systemProxy" in $$source)) {
            this["systemProxy"] = false;
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }
        if (!("coreService" in $$source)) {
            this["coreService"] = false;
        }
        if (!("tunReady" in $$source)) {
            this["tunReady"] = false;
        }
        if (!("dataDir" in $$source)) {
            this["dataDir"] = "";
        }
        if (!("generatedConfig" in $$source)) {
            this["generatedConfig"] = "";
        }
        if (!("platformMessage" in $$source)) {
            this["platformMessage"] = "";
        }
        if (!("needsPrivilege" in $$source)) {
            this["needsPrivilege"] = false;
        }
        if (!("supportedProxyApi" in $$source)) {
            this["supportedProxyApi"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PlatformStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlatformStatus($$parsedSource as Partial<PlatformStatus>);
    }
}

export class Policy {
    "id": string;
    "type": string;
    "name": string;
    "match": string;
    "domain": string[];
    "domainSuffix": string[];
    "domainKeyword": string[];
    "domainRegex": string[];
    "ipCidr": string[];
    "sourceIpCidr": string[];
    "port": string[];
    "portRange": string[];
    "sourcePort": string[];
    "sourcePortRange": string[];
    "processName": string[];
    "processPath": string[];
    "processPathRegex": string[];
    "packageName": string[];
    "protocol": string[];
    "queryType": string[];
    "network": string[];
    "networkType": string[];
    "defaultInterfaceAddress": string[];
    "wifiSsid": string[];
    "wifiBssid": string[];
    "networkIsExpensive": boolean;
    "networkIsConstrained": boolean;
    "ipIsPrivate": boolean;
    "ruleSet": string[];
    "raw_data"?: { [_ in string]?: any };
    "logical_rule"?: { [_ in string]?: any };
    "outbound": string;
    "enabled": boolean;
    "priority": number;
    "updatedAt": time$0.Time;

    /** Creates a new Policy instance. */
    constructor($$source: Partial<Policy> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("match" in $$source)) {
            this["match"] = "";
        }
        if (!("domain" in $$source)) {
            this["domain"] = [];
        }
        if (!("domainSuffix" in $$source)) {
            this["domainSuffix"] = [];
        }
        if (!("domainKeyword" in $$source)) {
            this["domainKeyword"] = [];
        }
        if (!("domainRegex" in $$source)) {
            this["domainRegex"] = [];
        }
        if (!("ipCidr" in $$source)) {
            this["ipCidr"] = [];
        }
        if (!("sourceIpCidr" in $$source)) {
            this["sourceIpCidr"] = [];
        }
        if (!("port" in $$source)) {
            this["port"] = [];
        }
        if (!("portRange" in $$source)) {
            this["portRange"] = [];
        }
        if (!("sourcePort" in $$source)) {
            this["sourcePort"] = [];
        }
        if (!("sourcePortRange" in $$source)) {
            this["sourcePortRange"] = [];
        }
        if (!("processName" in $$source)) {
            this["processName"] = [];
        }
        if (!("processPath" in $$source)) {
            this["processPath"] = [];
        }
        if (!("processPathRegex" in $$source)) {
            this["processPathRegex"] = [];
        }
        if (!("packageName" in $$source)) {
            this["packageName"] = [];
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = [];
        }
        if (!("queryType" in $$source)) {
            this["queryType"] = [];
        }
        if (!("network" in $$source)) {
            this["network"] = [];
        }
        if (!("networkType" in $$source)) {
            this["networkType"] = [];
        }
        if (!("defaultInterfaceAddress" in $$source)) {
            this["defaultInterfaceAddress"] = [];
        }
        if (!("wifiSsid" in $$source)) {
            this["wifiSsid"] = [];
        }
        if (!("wifiBssid" in $$source)) {
            this["wifiBssid"] = [];
        }
        if (!("networkIsExpensive" in $$source)) {
            this["networkIsExpensive"] = false;
        }
        if (!("networkIsConstrained" in $$source)) {
            this["networkIsConstrained"] = false;
        }
        if (!("ipIsPrivate" in $$source)) {
            this["ipIsPrivate"] = false;
        }
        if (!("ruleSet" in $$source)) {
            this["ruleSet"] = [];
        }
        if (!("outbound" in $$source)) {
            this["outbound"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Policy instance from a string or object.
     */
    static createFrom($$source: any = {}): Policy {
        const $$createField4_0 = $$createType10;
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType10;
        const $$createField7_0 = $$createType10;
        const $$createField8_0 = $$createType10;
        const $$createField9_0 = $$createType10;
        const $$createField10_0 = $$createType10;
        const $$createField11_0 = $$createType10;
        const $$createField12_0 = $$createType10;
        const $$createField13_0 = $$createType10;
        const $$createField14_0 = $$createType10;
        const $$createField15_0 = $$createType10;
        const $$createField16_0 = $$createType10;
        const $$createField17_0 = $$createType10;
        const $$createField18_0 = $$createType10;
        const $$createField19_0 = $$createType10;
        const $$createField20_0 = $$createType10;
        const $$createField21_0 = $$createType10;
        const $$createField22_0 = $$createType10;
        const $$createField23_0 = $$createType10;
        const $$createField24_0 = $$createType10;
        const $$createField28_0 = $$createType10;
        const $$createField29_0 = $$createType11;
        const $$createField30_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("domain" in $$parsedSource) {
            $$parsedSource["domain"] = $$createField4_0($$parsedSource["domain"]);
        }
        if ("domainSuffix" in $$parsedSource) {
            $$parsedSource["domainSuffix"] = $$createField5_0($$parsedSource["domainSuffix"]);
        }
        if ("domainKeyword" in $$parsedSource) {
            $$parsedSource["domainKeyword"] = $$createField6_0($$parsedSource["domainKeyword"]);
        }
        if ("domainRegex" in $$parsedSource) {
            $$parsedSource["domainRegex"] = $$createField7_0($$parsedSource["domainRegex"]);
        }
        if ("ipCidr" in $$parsedSource) {
            $$parsedSource["ipCidr"] = $$createField8_0($$parsedSource["ipCidr"]);
        }
        if ("sourceIpCidr" in $$parsedSource) {
            $$parsedSource["sourceIpCidr"] = $$createField9_0($$parsedSource["sourceIpCidr"]);
        }
        if ("port" in $$parsedSource) {
            $$parsedSource["port"] = $$createField10_0($$parsedSource["port"]);
        }
        if ("portRange" in $$parsedSource) {
            $$parsedSource["portRange"] = $$createField11_0($$parsedSource["portRange"]);
        }
        if ("sourcePort" in $$parsedSource) {
            $$parsedSource["sourcePort"] = $$createField12_0($$parsedSource["sourcePort"]);
        }
        if ("sourcePortRange" in $$parsedSource) {
            $$parsedSource["sourcePortRange"] = $$createField13_0($$parsedSource["sourcePortRange"]);
        }
        if ("processName" in $$parsedSource) {
            $$parsedSource["processName"] = $$createField14_0($$parsedSource["processName"]);
        }
        if ("processPath" in $$parsedSource) {
            $$parsedSource["processPath"] = $$createField15_0($$parsedSource["processPath"]);
        }
        if ("processPathRegex" in $$parsedSource) {
            $$parsedSource["processPathRegex"] = $$createField16_0($$parsedSource["processPathRegex"]);
        }
        if ("packageName" in $$parsedSource) {
            $$parsedSource["packageName"] = $$createField17_0($$parsedSource["packageName"]);
        }
        if ("protocol" in $$parsedSource) {
            $$parsedSource["protocol"] = $$createField18_0($$parsedSource["protocol"]);
        }
        if ("queryType" in $$parsedSource) {
            $$parsedSource["queryType"] = $$createField19_0($$parsedSource["queryType"]);
        }
        if ("network" in $$parsedSource) {
            $$parsedSource["network"] = $$createField20_0($$parsedSource["network"]);
        }
        if ("networkType" in $$parsedSource) {
            $$parsedSource["networkType"] = $$createField21_0($$parsedSource["networkType"]);
        }
        if ("defaultInterfaceAddress" in $$parsedSource) {
            $$parsedSource["defaultInterfaceAddress"] = $$createField22_0($$parsedSource["defaultInterfaceAddress"]);
        }
        if ("wifiSsid" in $$parsedSource) {
            $$parsedSource["wifiSsid"] = $$createField23_0($$parsedSource["wifiSsid"]);
        }
        if ("wifiBssid" in $$parsedSource) {
            $$parsedSource["wifiBssid"] = $$createField24_0($$parsedSource["wifiBssid"]);
        }
        if ("ruleSet" in $$parsedSource) {
            $$parsedSource["ruleSet"] = $$createField28_0($$parsedSource["ruleSet"]);
        }
        if ("raw_data" in $$parsedSource) {
            $$parsedSource["raw_data"] = $$createField29_0($$parsedSource["raw_data"]);
        }
        if ("logical_rule" in $$parsedSource) {
            $$parsedSource["logical_rule"] = $$createField30_0($$parsedSource["logical_rule"]);
        }
        return new Policy($$parsedSource as Partial<Policy>);
    }
}

export class PresetApplyResult {
    "added": number;
    "updated": number;

    /** Creates a new PresetApplyResult instance. */
    constructor($$source: Partial<PresetApplyResult> = {}) {
        if (!("added" in $$source)) {
            this["added"] = 0;
        }
        if (!("updated" in $$source)) {
            this["updated"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetApplyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PresetApplyResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresetApplyResult($$parsedSource as Partial<PresetApplyResult>);
    }
}

export class ProbeItem {
    "target": string;
    "status": string;
    "delay": number;

    /** Creates a new ProbeItem instance. */
    constructor($$source: Partial<ProbeItem> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("delay" in $$source)) {
            this["delay"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ProbeItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProbeItem($$parsedSource as Partial<ProbeItem>);
    }
}

export class Profile {
    "id": string;
    "name": string;
    "url": string;
    "content": string;
    "nodeCount": number;
    "selected": boolean;
    "updateInterval": number;
    "filter": string;
    "testUrl": string;
    "lastError": string;
    "lastUpdated": time$0.Time;
    "nodes": ProxyNode[];
    "proxyGroups": ProxyGroupConfig[];
    "customGroups": CustomProxyGroup[];
    "proxyProviders": ProxyProviderConfig[];
    "subscriptionUserinfo"?: SubscriptionUserinfo | null;
    "policyOverrides": ProfilePolicyOverride[];
    "dnsPolicyOverrides": ProfileDNSPolicyOverride[];
    "dnsServerDetours": ProfileDNSServerDetour[];

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("nodeCount" in $$source)) {
            this["nodeCount"] = 0;
        }
        if (!("selected" in $$source)) {
            this["selected"] = false;
        }
        if (!("updateInterval" in $$source)) {
            this["updateInterval"] = 0;
        }
        if (!("filter" in $$source)) {
            this["filter"] = "";
        }
        if (!("testUrl" in $$source)) {
            this["testUrl"] = "";
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = null;
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("proxyGroups" in $$source)) {
            this["proxyGroups"] = [];
        }
        if (!("customGroups" in $$source)) {
            this["customGroups"] = [];
        }
        if (!("proxyProviders" in $$source)) {
            this["proxyProviders"] = [];
        }
        if (!("policyOverrides" in $$source)) {
            this["policyOverrides"] = [];
        }
        if (!("dnsPolicyOverrides" in $$source)) {
            this["dnsPolicyOverrides"] = [];
        }
        if (!("dnsServerDetours" in $$source)) {
            this["dnsServerDetours"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        const $$createField11_0 = $$createType16;
        const $$createField12_0 = $$createType18;
        const $$createField13_0 = $$createType20;
        const $$createField14_0 = $$createType22;
        const $$createField15_0 = $$createType24;
        const $$createField16_0 = $$createType26;
        const $$createField17_0 = $$createType28;
        const $$createField18_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField11_0($$parsedSource["nodes"]);
        }
        if ("proxyGroups" in $$parsedSource) {
            $$parsedSource["proxyGroups"] = $$createField12_0($$parsedSource["proxyGroups"]);
        }
        if ("customGroups" in $$parsedSource) {
            $$parsedSource["customGroups"] = $$createField13_0($$parsedSource["customGroups"]);
        }
        if ("proxyProviders" in $$parsedSource) {
            $$parsedSource["proxyProviders"] = $$createField14_0($$parsedSource["proxyProviders"]);
        }
        if ("subscriptionUserinfo" in $$parsedSource) {
            $$parsedSource["subscriptionUserinfo"] = $$createField15_0($$parsedSource["subscriptionUserinfo"]);
        }
        if ("policyOverrides" in $$parsedSource) {
            $$parsedSource["policyOverrides"] = $$createField16_0($$parsedSource["policyOverrides"]);
        }
        if ("dnsPolicyOverrides" in $$parsedSource) {
            $$parsedSource["dnsPolicyOverrides"] = $$createField17_0($$parsedSource["dnsPolicyOverrides"]);
        }
        if ("dnsServerDetours" in $$parsedSource) {
            $$parsedSource["dnsServerDetours"] = $$createField18_0($$parsedSource["dnsServerDetours"]);
        }
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

export class ProfileDNSPolicyOverride {
    "policyId": string;
    "server": string;

    /** Creates a new ProfileDNSPolicyOverride instance. */
    constructor($$source: Partial<ProfileDNSPolicyOverride> = {}) {
        if (!("policyId" in $$source)) {
            this["policyId"] = "";
        }
        if (!("server" in $$source)) {
            this["server"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileDNSPolicyOverride instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileDNSPolicyOverride {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileDNSPolicyOverride($$parsedSource as Partial<ProfileDNSPolicyOverride>);
    }
}

export class ProfileDNSServerDetour {
    "serverId": string;
    "detour": string;

    /** Creates a new ProfileDNSServerDetour instance. */
    constructor($$source: Partial<ProfileDNSServerDetour> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("detour" in $$source)) {
            this["detour"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileDNSServerDetour instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileDNSServerDetour {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileDNSServerDetour($$parsedSource as Partial<ProfileDNSServerDetour>);
    }
}

export class ProfilePolicyOverride {
    "policyId": string;
    "outbound": string;

    /** Creates a new ProfilePolicyOverride instance. */
    constructor($$source: Partial<ProfilePolicyOverride> = {}) {
        if (!("policyId" in $$source)) {
            this["policyId"] = "";
        }
        if (!("outbound" in $$source)) {
            this["outbound"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfilePolicyOverride instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfilePolicyOverride {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfilePolicyOverride($$parsedSource as Partial<ProfilePolicyOverride>);
    }
}

export class ProxyGroup {
    "name": string;
    "type": string;
    "now": string;
    "all": ProxyNode[];
    "latency": number;

    /** Creates a new ProxyGroup instance. */
    constructor($$source: Partial<ProxyGroup> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("now" in $$source)) {
            this["now"] = "";
        }
        if (!("all" in $$source)) {
            this["all"] = [];
        }
        if (!("latency" in $$source)) {
            this["latency"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyGroup {
        const $$createField3_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("all" in $$parsedSource) {
            $$parsedSource["all"] = $$createField3_0($$parsedSource["all"]);
        }
        return new ProxyGroup($$parsedSource as Partial<ProxyGroup>);
    }
}

export class ProxyGroupConfig {
    "name": string;
    "type": string;
    "proxies": string[];
    "use": string[];
    "url": string;
    "strategy": string;
    "interval": number;
    "tolerance": number;

    /** Creates a new ProxyGroupConfig instance. */
    constructor($$source: Partial<ProxyGroupConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("proxies" in $$source)) {
            this["proxies"] = [];
        }
        if (!("use" in $$source)) {
            this["use"] = [];
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("strategy" in $$source)) {
            this["strategy"] = "";
        }
        if (!("interval" in $$source)) {
            this["interval"] = 0;
        }
        if (!("tolerance" in $$source)) {
            this["tolerance"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyGroupConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyGroupConfig {
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("proxies" in $$parsedSource) {
            $$parsedSource["proxies"] = $$createField2_0($$parsedSource["proxies"]);
        }
        if ("use" in $$parsedSource) {
            $$parsedSource["use"] = $$createField3_0($$parsedSource["use"]);
        }
        return new ProxyGroupConfig($$parsedSource as Partial<ProxyGroupConfig>);
    }
}

export class ProxyNode {
    "name": string;
    "type": string;
    "server": string;
    "port": number;
    "country": string;
    "latency": number;
    "selected": boolean;
    "raw": { [_ in string]?: any };

    /** Creates a new ProxyNode instance. */
    constructor($$source: Partial<ProxyNode> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("server" in $$source)) {
            this["server"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("country" in $$source)) {
            this["country"] = "";
        }
        if (!("latency" in $$source)) {
            this["latency"] = 0;
        }
        if (!("selected" in $$source)) {
            this["selected"] = false;
        }
        if (!("raw" in $$source)) {
            this["raw"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyNode instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyNode {
        const $$createField7_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("raw" in $$parsedSource) {
            $$parsedSource["raw"] = $$createField7_0($$parsedSource["raw"]);
        }
        return new ProxyNode($$parsedSource as Partial<ProxyNode>);
    }
}

export class ProxyProviderConfig {
    "name": string;
    "type": string;
    "url": string;
    "path": string;
    "interval": number;
    "filter": string;
    "healthCheckEnable": boolean;
    "healthCheckUrl": string;
    "healthCheckInterval": number;
    "nodeCount": number;
    "lastUpdated": time$0.Time;
    "lastChecked": time$0.Time;
    "lastError": string;
    "health": ProbeItem[];

    /** Creates a new ProxyProviderConfig instance. */
    constructor($$source: Partial<ProxyProviderConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("interval" in $$source)) {
            this["interval"] = 0;
        }
        if (!("filter" in $$source)) {
            this["filter"] = "";
        }
        if (!("healthCheckEnable" in $$source)) {
            this["healthCheckEnable"] = false;
        }
        if (!("healthCheckUrl" in $$source)) {
            this["healthCheckUrl"] = "";
        }
        if (!("healthCheckInterval" in $$source)) {
            this["healthCheckInterval"] = 0;
        }
        if (!("nodeCount" in $$source)) {
            this["nodeCount"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = null;
        }
        if (!("lastChecked" in $$source)) {
            this["lastChecked"] = null;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("health" in $$source)) {
            this["health"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyProviderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyProviderConfig {
        const $$createField13_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("health" in $$parsedSource) {
            $$parsedSource["health"] = $$createField13_0($$parsedSource["health"]);
        }
        return new ProxyProviderConfig($$parsedSource as Partial<ProxyProviderConfig>);
    }
}

export class RefreshScheduleItem {
    "kind": string;
    "id": string;
    "profileId": string;
    "providerName": string;
    "name": string;
    "enabled": boolean;
    "intervalHours": number;
    "intervalSeconds": number;
    "lastUpdated": time$0.Time;
    "nextRefresh": time$0.Time;
    "due": boolean;
    "lastError": string;

    /** Creates a new RefreshScheduleItem instance. */
    constructor($$source: Partial<RefreshScheduleItem> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("providerName" in $$source)) {
            this["providerName"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("intervalHours" in $$source)) {
            this["intervalHours"] = 0;
        }
        if (!("intervalSeconds" in $$source)) {
            this["intervalSeconds"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = null;
        }
        if (!("nextRefresh" in $$source)) {
            this["nextRefresh"] = null;
        }
        if (!("due" in $$source)) {
            this["due"] = false;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefreshScheduleItem instance from a string or object.
     */
    static createFrom($$source: any = {}): RefreshScheduleItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RefreshScheduleItem($$parsedSource as Partial<RefreshScheduleItem>);
    }
}

export class ReleaseManifest {
    "version": string;
    "buildNumber"?: string;
    "downloadUrl"?: string;
    "releaseUrl"?: string;
    "notes"?: string;
    "sha256"?: string;

    /** Creates a new ReleaseManifest instance. */
    constructor($$source: Partial<ReleaseManifest> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseManifest instance from a string or object.
     */
    static createFrom($$source: any = {}): ReleaseManifest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReleaseManifest($$parsedSource as Partial<ReleaseManifest>);
    }
}

export class RoverProfileDNSPolicyItem {
    "dns_policy_id": string;
    "preferred_server": string;

    /** Creates a new RoverProfileDNSPolicyItem instance. */
    constructor($$source: Partial<RoverProfileDNSPolicyItem> = {}) {
        if (!("dns_policy_id" in $$source)) {
            this["dns_policy_id"] = "";
        }
        if (!("preferred_server" in $$source)) {
            this["preferred_server"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoverProfileDNSPolicyItem instance from a string or object.
     */
    static createFrom($$source: any = {}): RoverProfileDNSPolicyItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoverProfileDNSPolicyItem($$parsedSource as Partial<RoverProfileDNSPolicyItem>);
    }
}

export class RoverProfileDNSServerItem {
    "dns_server_id": string;
    "preferred_detour": string;

    /** Creates a new RoverProfileDNSServerItem instance. */
    constructor($$source: Partial<RoverProfileDNSServerItem> = {}) {
        if (!("dns_server_id" in $$source)) {
            this["dns_server_id"] = "";
        }
        if (!("preferred_detour" in $$source)) {
            this["preferred_detour"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoverProfileDNSServerItem instance from a string or object.
     */
    static createFrom($$source: any = {}): RoverProfileDNSServerItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoverProfileDNSServerItem($$parsedSource as Partial<RoverProfileDNSServerItem>);
    }
}

export class RoverProfilePolicyItem {
    "policy_id": string;
    "preferred_outbound": string;

    /** Creates a new RoverProfilePolicyItem instance. */
    constructor($$source: Partial<RoverProfilePolicyItem> = {}) {
        if (!("policy_id" in $$source)) {
            this["policy_id"] = "";
        }
        if (!("preferred_outbound" in $$source)) {
            this["preferred_outbound"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoverProfilePolicyItem instance from a string or object.
     */
    static createFrom($$source: any = {}): RoverProfilePolicyItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoverProfilePolicyItem($$parsedSource as Partial<RoverProfilePolicyItem>);
    }
}

export class RuleProviderDownloadResult {
    "success": boolean;
    "path"?: string;
    "error"?: string;

    /** Creates a new RuleProviderDownloadResult instance. */
    constructor($$source: Partial<RuleProviderDownloadResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleProviderDownloadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RuleProviderDownloadResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuleProviderDownloadResult($$parsedSource as Partial<RuleProviderDownloadResult>);
    }
}

export class RuleProviderViewContent {
    "content"?: string;
    "error"?: string;

    /** Creates a new RuleProviderViewContent instance. */
    constructor($$source: Partial<RuleProviderViewContent> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleProviderViewContent instance from a string or object.
     */
    static createFrom($$source: any = {}): RuleProviderViewContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuleProviderViewContent($$parsedSource as Partial<RuleProviderViewContent>);
    }
}

export class RuleSet {
    "id": string;
    "tag": string;
    "type": string;
    "format": string;
    "behavior": string;
    "url": string;
    "path": string;
    "localPath": string;
    "downloadDetour": string;
    "enabled": boolean;
    "profileId"?: string;
    "lastUpdated": time$0.Time;
    "lastError": string;
    "lastWarning": string;

    /** Creates a new RuleSet instance. */
    constructor($$source: Partial<RuleSet> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("behavior" in $$source)) {
            this["behavior"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("localPath" in $$source)) {
            this["localPath"] = "";
        }
        if (!("downloadDetour" in $$source)) {
            this["downloadDetour"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = null;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("lastWarning" in $$source)) {
            this["lastWarning"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleSet instance from a string or object.
     */
    static createFrom($$source: any = {}): RuleSet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuleSet($$parsedSource as Partial<RuleSet>);
    }
}

export class RuleSetGroup {
    "groupKey": string;
    "displayName": string;
    "items": RuleSet[];

    /** Creates a new RuleSetGroup instance. */
    constructor($$source: Partial<RuleSetGroup> = {}) {
        if (!("groupKey" in $$source)) {
            this["groupKey"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleSetGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): RuleSetGroup {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField2_0($$parsedSource["items"]);
        }
        return new RuleSetGroup($$parsedSource as Partial<RuleSetGroup>);
    }
}

export class SelectedProfileState {
    "found": boolean;
    "profile": Profile;
    "config": { [_ in string]?: any };

    /** Creates a new SelectedProfileState instance. */
    constructor($$source: Partial<SelectedProfileState> = {}) {
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("profile" in $$source)) {
            this["profile"] = (new Profile());
        }
        if (!("config" in $$source)) {
            this["config"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectedProfileState instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectedProfileState {
        const $$createField1_0 = $$createType31;
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profile" in $$parsedSource) {
            $$parsedSource["profile"] = $$createField1_0($$parsedSource["profile"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        return new SelectedProfileState($$parsedSource as Partial<SelectedProfileState>);
    }
}

export class Settings {
    "apiPort": number;
    "apiSecret": string;
    "mixedPort": number;
    "mixedListen": string;
    "allowLan": boolean;
    "subscriptionUserAgent": string;
    "ipv6"?: boolean | null;
    "overrideRules"?: boolean | null;
    "autoStartProxy"?: boolean | null;
    "customProxyGroups": boolean;
    "tunEnabled": boolean;
    "tunStack": string;
    "tunInterfaceName": string;
    "tunAddress": string[];
    "tunMTU": number;
    "tunAutoRoute"?: boolean | null;
    "tunStrictRoute"?: boolean | null;
    "tunAutoDetectInterface"?: boolean | null;
    "tunDNSHijack": string[];
    "tunRouteAddress": string[];
    "tunRouteExcludeAddress": string[];
    "autoStart": boolean;
    "systemProxy": boolean;
    "sniffEnabled": boolean;
    "sniffOverrideDestination": boolean;
    "mode": string;
    "logLevel": string;
    "singBoxPath": string;
    "dnsListen": string;
    "dnsStrategy": string;
    "dnsIPv6"?: boolean | null;
    "dnsFakeIPEnabled": boolean;
    "dnsFakeIPRange": string;
    "dnsFakeIPv6Range": string;
    "dnsFakeIPFilter": string[];
    "dnsFallbackFilter": { [_ in string]?: any };
    "finalOutbound": string;
    "hosts": { [_ in string]?: string[] };
    "experimental": { [_ in string]?: any };

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("apiPort" in $$source)) {
            this["apiPort"] = 0;
        }
        if (!("apiSecret" in $$source)) {
            this["apiSecret"] = "";
        }
        if (!("mixedPort" in $$source)) {
            this["mixedPort"] = 0;
        }
        if (!("mixedListen" in $$source)) {
            this["mixedListen"] = "";
        }
        if (!("allowLan" in $$source)) {
            this["allowLan"] = false;
        }
        if (!("subscriptionUserAgent" in $$source)) {
            this["subscriptionUserAgent"] = "";
        }
        if (!("customProxyGroups" in $$source)) {
            this["customProxyGroups"] = false;
        }
        if (!("tunEnabled" in $$source)) {
            this["tunEnabled"] = false;
        }
        if (!("tunStack" in $$source)) {
            this["tunStack"] = "";
        }
        if (!("tunInterfaceName" in $$source)) {
            this["tunInterfaceName"] = "";
        }
        if (!("tunAddress" in $$source)) {
            this["tunAddress"] = [];
        }
        if (!("tunMTU" in $$source)) {
            this["tunMTU"] = 0;
        }
        if (!("tunDNSHijack" in $$source)) {
            this["tunDNSHijack"] = [];
        }
        if (!("tunRouteAddress" in $$source)) {
            this["tunRouteAddress"] = [];
        }
        if (!("tunRouteExcludeAddress" in $$source)) {
            this["tunRouteExcludeAddress"] = [];
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }
        if (!("systemProxy" in $$source)) {
            this["systemProxy"] = false;
        }
        if (!("sniffEnabled" in $$source)) {
            this["sniffEnabled"] = false;
        }
        if (!("sniffOverrideDestination" in $$source)) {
            this["sniffOverrideDestination"] = false;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("logLevel" in $$source)) {
            this["logLevel"] = "";
        }
        if (!("singBoxPath" in $$source)) {
            this["singBoxPath"] = "";
        }
        if (!("dnsListen" in $$source)) {
            this["dnsListen"] = "";
        }
        if (!("dnsStrategy" in $$source)) {
            this["dnsStrategy"] = "";
        }
        if (!("dnsFakeIPEnabled" in $$source)) {
            this["dnsFakeIPEnabled"] = false;
        }
        if (!("dnsFakeIPRange" in $$source)) {
            this["dnsFakeIPRange"] = "";
        }
        if (!("dnsFakeIPv6Range" in $$source)) {
            this["dnsFakeIPv6Range"] = "";
        }
        if (!("dnsFakeIPFilter" in $$source)) {
            this["dnsFakeIPFilter"] = [];
        }
        if (!("dnsFallbackFilter" in $$source)) {
            this["dnsFallbackFilter"] = {};
        }
        if (!("finalOutbound" in $$source)) {
            this["finalOutbound"] = "";
        }
        if (!("hosts" in $$source)) {
            this["hosts"] = {};
        }
        if (!("experimental" in $$source)) {
            this["experimental"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField13_0 = $$createType10;
        const $$createField18_0 = $$createType10;
        const $$createField19_0 = $$createType10;
        const $$createField20_0 = $$createType10;
        const $$createField34_0 = $$createType10;
        const $$createField35_0 = $$createType11;
        const $$createField37_0 = $$createType32;
        const $$createField38_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tunAddress" in $$parsedSource) {
            $$parsedSource["tunAddress"] = $$createField13_0($$parsedSource["tunAddress"]);
        }
        if ("tunDNSHijack" in $$parsedSource) {
            $$parsedSource["tunDNSHijack"] = $$createField18_0($$parsedSource["tunDNSHijack"]);
        }
        if ("tunRouteAddress" in $$parsedSource) {
            $$parsedSource["tunRouteAddress"] = $$createField19_0($$parsedSource["tunRouteAddress"]);
        }
        if ("tunRouteExcludeAddress" in $$parsedSource) {
            $$parsedSource["tunRouteExcludeAddress"] = $$createField20_0($$parsedSource["tunRouteExcludeAddress"]);
        }
        if ("dnsFakeIPFilter" in $$parsedSource) {
            $$parsedSource["dnsFakeIPFilter"] = $$createField34_0($$parsedSource["dnsFakeIPFilter"]);
        }
        if ("dnsFallbackFilter" in $$parsedSource) {
            $$parsedSource["dnsFallbackFilter"] = $$createField35_0($$parsedSource["dnsFallbackFilter"]);
        }
        if ("hosts" in $$parsedSource) {
            $$parsedSource["hosts"] = $$createField37_0($$parsedSource["hosts"]);
        }
        if ("experimental" in $$parsedSource) {
            $$parsedSource["experimental"] = $$createField38_0($$parsedSource["experimental"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class SingBoxRuntimeStatus {
    "success": boolean;
    "data"?: SingBoxRuntimeStatusData;
    "error"?: string;
    "message"?: string;

    /** Creates a new SingBoxRuntimeStatus instance. */
    constructor($$source: Partial<SingBoxRuntimeStatus> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SingBoxRuntimeStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SingBoxRuntimeStatus {
        const $$createField1_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new SingBoxRuntimeStatus($$parsedSource as Partial<SingBoxRuntimeStatus>);
    }
}

export class SingBoxRuntimeStatusData {
    "running": boolean;
    "pid"?: number;
    "startTime"?: number;
    "configPath"?: string;
    "binaryPath"?: string;

    /** Creates a new SingBoxRuntimeStatusData instance. */
    constructor($$source: Partial<SingBoxRuntimeStatusData> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SingBoxRuntimeStatusData instance from a string or object.
     */
    static createFrom($$source: any = {}): SingBoxRuntimeStatusData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SingBoxRuntimeStatusData($$parsedSource as Partial<SingBoxRuntimeStatusData>);
    }
}

export class SubscriptionUserinfo {
    "upload": number;
    "download": number;
    "total": number;
    "expire": number;

    /** Creates a new SubscriptionUserinfo instance. */
    constructor($$source: Partial<SubscriptionUserinfo> = {}) {
        if (!("upload" in $$source)) {
            this["upload"] = 0;
        }
        if (!("download" in $$source)) {
            this["download"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("expire" in $$source)) {
            this["expire"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubscriptionUserinfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SubscriptionUserinfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubscriptionUserinfo($$parsedSource as Partial<SubscriptionUserinfo>);
    }
}

export class TemplateImportResult {
    "success": boolean;
    "message": string;
    "addedCount": number;
    "presetResult"?: PresetApplyResult | null;
    "dnsSet": boolean;
    "finalOutboundSet": boolean;
    "finalOutbound"?: string;
    "tunSet": boolean;
    "tunNeedsAdmin": boolean;
    "tunValue": boolean;
    "defaultDnsServerSet": boolean;

    /** Creates a new TemplateImportResult instance. */
    constructor($$source: Partial<TemplateImportResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("addedCount" in $$source)) {
            this["addedCount"] = 0;
        }
        if (!("dnsSet" in $$source)) {
            this["dnsSet"] = false;
        }
        if (!("finalOutboundSet" in $$source)) {
            this["finalOutboundSet"] = false;
        }
        if (!("tunSet" in $$source)) {
            this["tunSet"] = false;
        }
        if (!("tunNeedsAdmin" in $$source)) {
            this["tunNeedsAdmin"] = false;
        }
        if (!("tunValue" in $$source)) {
            this["tunValue"] = false;
        }
        if (!("defaultDnsServerSet" in $$source)) {
            this["defaultDnsServerSet"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplateImportResult {
        const $$createField3_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presetResult" in $$parsedSource) {
            $$parsedSource["presetResult"] = $$createField3_0($$parsedSource["presetResult"]);
        }
        return new TemplateImportResult($$parsedSource as Partial<TemplateImportResult>);
    }
}

export class TemplatePolicyPayload {
    "policies": Policy[];
    "dnsServers": DNSServer[];
    "dnsPolicies": DNSPolicy[];
    "settings": { [_ in string]?: string };

    /** Creates a new TemplatePolicyPayload instance. */
    constructor($$source: Partial<TemplatePolicyPayload> = {}) {
        if (!("policies" in $$source)) {
            this["policies"] = [];
        }
        if (!("dnsServers" in $$source)) {
            this["dnsServers"] = [];
        }
        if (!("dnsPolicies" in $$source)) {
            this["dnsPolicies"] = [];
        }
        if (!("settings" in $$source)) {
            this["settings"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplatePolicyPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplatePolicyPayload {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("policies" in $$parsedSource) {
            $$parsedSource["policies"] = $$createField0_0($$parsedSource["policies"]);
        }
        if ("dnsServers" in $$parsedSource) {
            $$parsedSource["dnsServers"] = $$createField1_0($$parsedSource["dnsServers"]);
        }
        if ("dnsPolicies" in $$parsedSource) {
            $$parsedSource["dnsPolicies"] = $$createField2_0($$parsedSource["dnsPolicies"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField3_0($$parsedSource["settings"]);
        }
        return new TemplatePolicyPayload($$parsedSource as Partial<TemplatePolicyPayload>);
    }
}

export class TemplateSummary {
    "name": string;
    "description": string;
    "path": string;

    /** Creates a new TemplateSummary instance. */
    constructor($$source: Partial<TemplateSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplateSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplateSummary($$parsedSource as Partial<TemplateSummary>);
    }
}

export class TrafficState {
    "upload": number;
    "download": number;
    "live": boolean;

    /** Creates a new TrafficState instance. */
    constructor($$source: Partial<TrafficState> = {}) {
        if (!("upload" in $$source)) {
            this["upload"] = 0;
        }
        if (!("download" in $$source)) {
            this["download"] = 0;
        }
        if (!("live" in $$source)) {
            this["live"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrafficState instance from a string or object.
     */
    static createFrom($$source: any = {}): TrafficState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrafficState($$parsedSource as Partial<TrafficState>);
    }
}

export class UpdateCheckResult {
    "available": boolean;
    "currentVersion": string;
    "latestVersion": string;
    "manifest": ReleaseManifest;
    "source": string;
    "error"?: string;

    /** Creates a new UpdateCheckResult instance. */
    constructor($$source: Partial<UpdateCheckResult> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("manifest" in $$source)) {
            this["manifest"] = (new ReleaseManifest());
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCheckResult {
        const $$createField3_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField3_0($$parsedSource["manifest"]);
        }
        return new UpdateCheckResult($$parsedSource as Partial<UpdateCheckResult>);
    }
}

// Private type creation functions
const $$createType0 = Policy.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = RuleSet.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = DNSServer.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = DNSPolicy.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Settings.createFrom;
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
const $$createType12 = DNSRuntimeStatusData.createFrom;
const $$createType13 = ProbeItem.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = ProxyNode.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = ProxyGroupConfig.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = CustomProxyGroup.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = ProxyProviderConfig.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = SubscriptionUserinfo.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = ProfilePolicyOverride.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = ProfileDNSPolicyOverride.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = ProfileDNSServerDetour.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = Profile.createFrom;
const $$createType32 = $Create.Map($Create.Any, $$createType10);
const $$createType33 = SingBoxRuntimeStatusData.createFrom;
const $$createType34 = PresetApplyResult.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = ReleaseManifest.createFrom;
