// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddDnsPolicy(policy: $models.DNSPolicy): $CancellablePromise<string> {
    return $Call.ByID(1521711442, policy);
}

export function AddDnsServer(server: $models.DNSServer): $CancellablePromise<string> {
    return $Call.ByID(2719522547, server);
}

export function AddNodeToProfile(profileID: string, node: $models.ProxyNode): $CancellablePromise<$models.ProxyNode> {
    return $Call.ByID(2453191845, profileID, node).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AddPoliciesBatch(policies: $models.Policy[], clearFirst: boolean): $CancellablePromise<number> {
    return $Call.ByID(1198399333, policies, clearFirst);
}

export function AddPolicy(policy: $models.Policy): $CancellablePromise<string> {
    return $Call.ByID(2084260659, policy);
}

export function AddProfile(profile: $models.Profile): $CancellablePromise<string> {
    return $Call.ByID(3353449866, profile);
}

export function AddProfileCustomGroup(profileID: string, group: $models.CustomProxyGroup): $CancellablePromise<void> {
    return $Call.ByID(2659919336, profileID, group);
}

export function AddProfileGroup(profileID: string, group: $models.ProxyGroupConfig): $CancellablePromise<$models.ProxyGroupConfig> {
    return $Call.ByID(2400955741, profileID, group).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AddRuleProvidersFromPreset(ids: string[]): $CancellablePromise<$models.PresetApplyResult> {
    return $Call.ByID(3695628700, ids).then(($result: any) => {
        return $$createType2($result);
    });
}

export function AddRuleSetsFromPreset(ids: string[]): $CancellablePromise<$models.PresetApplyResult> {
    return $Call.ByID(2059774197, ids).then(($result: any) => {
        return $$createType2($result);
    });
}

export function AddSubscriptionProfile(url: string): $CancellablePromise<string> {
    return $Call.ByID(4205830093, url);
}

export function ApplyBuiltinTemplate(id: string, replace: boolean): $CancellablePromise<void> {
    return $Call.ByID(195221939, id, replace);
}

export function ApplyPlatformSettings(): $CancellablePromise<void> {
    return $Call.ByID(1697316572);
}

export function CheckForUpdates(source: string): $CancellablePromise<$models.UpdateCheckResult> {
    return $Call.ByID(2714807417, source).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ClearAllLogs(): $CancellablePromise<void> {
    return $Call.ByID(475857781);
}

export function ClearCoreLog(): $CancellablePromise<void> {
    return $Call.ByID(124050114);
}

export function ClearLog(): $CancellablePromise<$models.ClearOperationResult> {
    return $Call.ByID(4051164475).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(1739675736);
}

export function ClearProfileCustomGroups(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(214188287, profileID);
}

export function ClearProfileDNSPolicyOverride(profileID: string, policyID: string): $CancellablePromise<void> {
    return $Call.ByID(530229701, profileID, policyID);
}

export function ClearProfileDNSServerDetour(profileID: string, serverID: string): $CancellablePromise<void> {
    return $Call.ByID(3821781785, profileID, serverID);
}

export function ClearProfilePolicyOverride(profileID: string, policyID: string): $CancellablePromise<void> {
    return $Call.ByID(748797838, profileID, policyID);
}

export function CloseAllConnections(): $CancellablePromise<void> {
    return $Call.ByID(277993782);
}

export function CloseConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(886648026, id);
}

export function DeleteDNSPolicy(id: string): $CancellablePromise<void> {
    return $Call.ByID(485378286, id);
}

export function DeleteDNSServer(id: string): $CancellablePromise<void> {
    return $Call.ByID(976695671, id);
}

export function DeleteDnsPolicy(id: string): $CancellablePromise<void> {
    return $Call.ByID(519967918, id);
}

export function DeleteDnsServer(id: string): $CancellablePromise<void> {
    return $Call.ByID(2650995255, id);
}

export function DeletePolicy(id: string): $CancellablePromise<void> {
    return $Call.ByID(1264537815, id);
}

export function DeletePreference(key: string): $CancellablePromise<void> {
    return $Call.ByID(925303908, key);
}

export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(2221941958, id);
}

export function DeleteProfileCustomGroup(profileID: string, groupName: string): $CancellablePromise<void> {
    return $Call.ByID(1439551300, profileID, groupName);
}

export function DeleteProfileGroup(profileID: string, index: number): $CancellablePromise<void> {
    return $Call.ByID(2409721913, profileID, index);
}

export function DeleteProfileNode(profileID: string, index: number): $CancellablePromise<void> {
    return $Call.ByID(1309896242, profileID, index);
}

export function DeleteRuleProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(643355274, id);
}

export function DeleteRuleSet(id: string): $CancellablePromise<void> {
    return $Call.ByID(4018119529, id);
}

export function DetectSingBox(): $CancellablePromise<string> {
    return $Call.ByID(1598413787);
}

export function DownloadRuleProvider(id: string): $CancellablePromise<$models.RuleProviderDownloadResult> {
    return $Call.ByID(2750753953, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Export(): $CancellablePromise<$models.ConfigOperationResult> {
    return $Call.ByID(121753056).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ExportConfig(): $CancellablePromise<$models.ConfigOperationResult> {
    return $Call.ByID(1742766510).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ExportConfigBackup(): $CancellablePromise<string> {
    return $Call.ByID(2046104104);
}

export function ExportConfigSnapshot(): $CancellablePromise<string> {
    return $Call.ByID(2419086930);
}

export function FetchIPDirect(): $CancellablePromise<$models.IPInfo | null> {
    return $Call.ByID(2545299838).then(($result: any) => {
        return $$createType8($result);
    });
}

export function FetchIPThroughProxy(): $CancellablePromise<$models.IPInfo | null> {
    return $Call.ByID(1045551484).then(($result: any) => {
        return $$createType8($result);
    });
}

export function FetchIpDirect(): $CancellablePromise<$models.IPInfo | null> {
    return $Call.ByID(267978718).then(($result: any) => {
        return $$createType8($result);
    });
}

export function FetchIpThroughProxy(): $CancellablePromise<$models.IPInfo | null> {
    return $Call.ByID(2659915420).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GenerateConfig(): $CancellablePromise<string> {
    return $Call.ByID(2625493159);
}

export function GetActiveConfig(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1932659622).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetAllProfileDnsServerDetours(profileID: string): $CancellablePromise<$models.RoverProfileDNSServerItem[]> {
    return $Call.ByID(824191492, profileID).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetAllRuleSetsGrouped(): $CancellablePromise<$models.RuleSetGroup[]> {
    return $Call.ByID(3640836632).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetAllSettings(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1388134272).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetAutoLaunch(): $CancellablePromise<boolean> {
    return $Call.ByID(3070877114);
}

export function GetAvailableOutbounds(): $CancellablePromise<$models.AvailableOutbound[]> {
    return $Call.ByID(660543706).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetBuildInfo(): $CancellablePromise<$models.BuildInfo> {
    return $Call.ByID(3410841158).then(($result: any) => {
        return $$createType17($result);
    });
}

export function GetBuiltinTemplates(): $CancellablePromise<$models.BuiltinTemplate[]> {
    return $Call.ByID(596968692).then(($result: any) => {
        return $$createType19($result);
    });
}

export function GetConnections(): $CancellablePromise<$models.Connection[]> {
    return $Call.ByID(2340236315).then(($result: any) => {
        return $$createType21($result);
    });
}

export function GetCoreServiceStatus(): $CancellablePromise<$models.CoreServiceStatus> {
    return $Call.ByID(2203353186).then(($result: any) => {
        return $$createType22($result);
    });
}

export function GetCurrentConfigRules(): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(3973849344).then(($result: any) => {
        return $$createType23($result);
    });
}

export function GetDNSPolicies(): $CancellablePromise<$models.DNSPolicy[]> {
    return $Call.ByID(1291052371).then(($result: any) => {
        return $$createType25($result);
    });
}

export function GetDNSServerRefs(tag: string): $CancellablePromise<$models.DNSServerRef[]> {
    return $Call.ByID(2759787092, tag).then(($result: any) => {
        return $$createType27($result);
    });
}

export function GetDNSServers(): $CancellablePromise<$models.DNSServer[]> {
    return $Call.ByID(4102568023).then(($result: any) => {
        return $$createType29($result);
    });
}

export function GetDNSStatus(): $CancellablePromise<$models.DNSRuntimeStatus> {
    return $Call.ByID(4265794043).then(($result: any) => {
        return $$createType30($result);
    });
}

export function GetDashboard(): $CancellablePromise<$models.DashboardState> {
    return $Call.ByID(3408125550).then(($result: any) => {
        return $$createType31($result);
    });
}

export function GetDatabaseStatus(): $CancellablePromise<$models.DatabaseStatus> {
    return $Call.ByID(4191305221).then(($result: any) => {
        return $$createType32($result);
    });
}

export function GetDnsPolicies(): $CancellablePromise<$models.DNSPolicy[]> {
    return $Call.ByID(2265175251).then(($result: any) => {
        return $$createType25($result);
    });
}

export function GetDnsServerRefs(tag: string): $CancellablePromise<$models.DNSServerRef[]> {
    return $Call.ByID(3962256852, tag).then(($result: any) => {
        return $$createType27($result);
    });
}

export function GetDnsServers(): $CancellablePromise<$models.DNSServer[]> {
    return $Call.ByID(3385604823).then(($result: any) => {
        return $$createType29($result);
    });
}

export function GetDnsStatus(): $CancellablePromise<$models.DNSRuntimeStatus> {
    return $Call.ByID(890920315).then(($result: any) => {
        return $$createType30($result);
    });
}

export function GetInitialLogLineCount(): $CancellablePromise<$models.InitialLogLineCount> {
    return $Call.ByID(57365089).then(($result: any) => {
        return $$createType33($result);
    });
}

export function GetInstallationStatus(): $CancellablePromise<$models.CoreServiceStatus> {
    return $Call.ByID(2562169120).then(($result: any) => {
        return $$createType22($result);
    });
}

export function GetLogDir(): $CancellablePromise<string> {
    return $Call.ByID(2750000955);
}

export function GetLogFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(418932435).then(($result: any) => {
        return $$createType34($result);
    });
}

export function GetLogs(): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(3154471189).then(($result: any) => {
        return $$createType36($result);
    });
}

export function GetPlatformStatus(): $CancellablePromise<$models.PlatformStatus> {
    return $Call.ByID(2111513159).then(($result: any) => {
        return $$createType37($result);
    });
}

export function GetPolicies(): $CancellablePromise<$models.Policy[]> {
    return $Call.ByID(2371233828).then(($result: any) => {
        return $$createType39($result);
    });
}

export function GetPreference(key: string, defaultValue: string): $CancellablePromise<string> {
    return $Call.ByID(394503727, key, defaultValue);
}

export function GetPreferences(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1614734036).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetPresetRuleSets(): $CancellablePromise<$models.RuleSet[]> {
    return $Call.ByID(4007523886).then(($result: any) => {
        return $$createType41($result);
    });
}

export function GetPresetRulesets(): $CancellablePromise<$models.RuleSet[]> {
    return $Call.ByID(1438485838).then(($result: any) => {
        return $$createType41($result);
    });
}

export function GetProfileContent(profileID: string): $CancellablePromise<string> {
    return $Call.ByID(2626843476, profileID);
}

export function GetProfileCustomGroups(profileID: string): $CancellablePromise<$models.CustomProxyGroup[]> {
    return $Call.ByID(43926128, profileID).then(($result: any) => {
        return $$createType43($result);
    });
}

export function GetProfileDnsPolicyByPolicyId(profileID: string, dnsPolicyID: string): $CancellablePromise<$models.RoverProfileDNSPolicyItem | null> {
    return $Call.ByID(1805494850, profileID, dnsPolicyID).then(($result: any) => {
        return $$createType45($result);
    });
}

export function GetProfileDnsServerDetour(profileID: string, dnsServerID: string): $CancellablePromise<string> {
    return $Call.ByID(3197351408, profileID, dnsServerID);
}

export function GetProfileNodes(profileID: string): $CancellablePromise<$models.ProxyNode[]> {
    return $Call.ByID(1434569264, profileID).then(($result: any) => {
        return $$createType46($result);
    });
}

export function GetProfilePolicyByPolicyId(profileID: string, policyID: string): $CancellablePromise<$models.RoverProfilePolicyItem | null> {
    return $Call.ByID(3311658339, profileID, policyID).then(($result: any) => {
        return $$createType48($result);
    });
}

export function GetProfiles(): $CancellablePromise<$models.Profile[]> {
    return $Call.ByID(2262137152).then(($result: any) => {
        return $$createType50($result);
    });
}

export function GetProxyDelay(name: string, testURL: string, timeout: number): $CancellablePromise<number> {
    return $Call.ByID(2056945517, name, testURL, timeout);
}

export function GetProxyGroups(): $CancellablePromise<$models.ProxyGroup[]> {
    return $Call.ByID(3092131434).then(($result: any) => {
        return $$createType52($result);
    });
}

export function GetProxyProviderContent(profileID: string, providerName: string): $CancellablePromise<string> {
    return $Call.ByID(4260360912, profileID, providerName);
}

export function GetRefreshSchedule(): $CancellablePromise<$models.RefreshScheduleItem[]> {
    return $Call.ByID(1561220956).then(($result: any) => {
        return $$createType54($result);
    });
}

export function GetRuleProviderViewContent(id: string): $CancellablePromise<$models.RuleProviderViewContent> {
    return $Call.ByID(2827966285, id).then(($result: any) => {
        return $$createType55($result);
    });
}

export function GetRuleProviders(): $CancellablePromise<$models.RuleSet[]> {
    return $Call.ByID(413334834).then(($result: any) => {
        return $$createType41($result);
    });
}

export function GetRuleSetContent(id: string): $CancellablePromise<$models.ConfigPreview> {
    return $Call.ByID(1260829085, id).then(($result: any) => {
        return $$createType56($result);
    });
}

export function GetRuleSets(): $CancellablePromise<$models.RuleSet[]> {
    return $Call.ByID(2387437969).then(($result: any) => {
        return $$createType41($result);
    });
}

export function GetSelectedProfile(): $CancellablePromise<$models.SelectedProfileState> {
    return $Call.ByID(3529690312).then(($result: any) => {
        return $$createType57($result);
    });
}

export function GetSetting(key: string, defaultValue: string): $CancellablePromise<string> {
    return $Call.ByID(2788136106, key, defaultValue);
}

export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(1978093979).then(($result: any) => {
        return $$createType58($result);
    });
}

export function GetSingBoxStatus(): $CancellablePromise<$models.SingBoxRuntimeStatus> {
    return $Call.ByID(663540384).then(($result: any) => {
        return $$createType59($result);
    });
}

export function GetSingboxStatus(): $CancellablePromise<$models.SingBoxRuntimeStatus> {
    return $Call.ByID(3220283648).then(($result: any) => {
        return $$createType59($result);
    });
}

export function GetStartTime(): $CancellablePromise<number | null> {
    return $Call.ByID(2769953783);
}

export function GetSystemProxyStatus(): $CancellablePromise<boolean> {
    return $Call.ByID(2786361723);
}

export function GetTemplatePolicies(templatePath: string): $CancellablePromise<$models.TemplatePolicyPayload> {
    return $Call.ByID(2338361402, templatePath).then(($result: any) => {
        return $$createType60($result);
    });
}

export function GetTemplates(): $CancellablePromise<$models.TemplateSummary[]> {
    return $Call.ByID(3724626729).then(($result: any) => {
        return $$createType62($result);
    });
}

export function GetTraffic(): $CancellablePromise<$models.TrafficState> {
    return $Call.ByID(3545819259).then(($result: any) => {
        return $$createType63($result);
    });
}

export function Import(path: string): $CancellablePromise<$models.ConfigOperationResult> {
    return $Call.ByID(2783088895, path).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ImportClashConfig(content: string, replace: boolean): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(3645573134, content, replace).then(($result: any) => {
        return $$createType64($result);
    });
}

export function ImportClashConfigFile(path: string, replace: boolean): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(2678899752, path, replace).then(($result: any) => {
        return $$createType64($result);
    });
}

export function ImportConfig(path: string): $CancellablePromise<$models.ConfigOperationResult> {
    return $Call.ByID(1142281165, path).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ImportConfigBackup(path: string): $CancellablePromise<void> {
    return $Call.ByID(113365079, path);
}

export function ImportConfigSnapshot(path: string): $CancellablePromise<void> {
    return $Call.ByID(98232677, path);
}

export function ImportLocalProfile(): $CancellablePromise<$models.Profile> {
    return $Call.ByID(1832182307).then(($result: any) => {
        return $$createType49($result);
    });
}

export function ImportProfile(name: string, source: string): $CancellablePromise<$models.Profile> {
    return $Call.ByID(1426939920, name, source).then(($result: any) => {
        return $$createType49($result);
    });
}

export function ImportProfileFile(name: string, path: string): $CancellablePromise<$models.Profile> {
    return $Call.ByID(1640538182, name, path).then(($result: any) => {
        return $$createType49($result);
    });
}

export function ImportSingBoxConfig(content: string, replace: boolean): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(4038130223, content, replace).then(($result: any) => {
        return $$createType64($result);
    });
}

export function ImportSingBoxConfigFile(path: string, replace: boolean): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(108092129, path, replace).then(($result: any) => {
        return $$createType64($result);
    });
}

export function ImportTemplateComplete(templatePath: string): $CancellablePromise<$models.TemplateImportResult> {
    return $Call.ByID(3770428746, templatePath).then(($result: any) => {
        return $$createType65($result);
    });
}

export function Install(): $CancellablePromise<$models.LauncherTaskResult> {
    return $Call.ByID(872605361).then(($result: any) => {
        return $$createType66($result);
    });
}

export function InstallCoreService(): $CancellablePromise<void> {
    return $Call.ByID(73136657);
}

export function InstallLauncherTask(): $CancellablePromise<$models.LauncherTaskResult> {
    return $Call.ByID(680534436).then(($result: any) => {
        return $$createType66($result);
    });
}

export function IsLauncherAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(4067004473);
}

export function IsLauncherTaskInstalled(): $CancellablePromise<boolean> {
    return $Call.ByID(291375423);
}

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1305313493);
}

export function IsServiceInstalled(): $CancellablePromise<boolean> {
    return $Call.ByID(833202345);
}

export function Log(level: string, $module: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1455394024, level, $module, message);
}

export function LogBatch(entries: $models.LogInput[]): $CancellablePromise<void> {
    return $Call.ByID(361481664, entries);
}

export function MoveProfileGroup(profileID: string, index: number, direction: number): $CancellablePromise<void> {
    return $Call.ByID(678461811, profileID, index, direction);
}

export function MoveProfileNode(profileID: string, index: number, direction: number): $CancellablePromise<void> {
    return $Call.ByID(4140955420, profileID, index, direction);
}

export function OnShutdown(): $CancellablePromise<void> {
    return $Call.ByID(1146949889);
}

export function OnStartup(options: application$0.ServiceOptions): $CancellablePromise<void> {
    return $Call.ByID(2627695516, options);
}

export function OpenCoreLog(): $CancellablePromise<void> {
    return $Call.ByID(941360233);
}

export function OpenDataDir(): $CancellablePromise<void> {
    return $Call.ByID(1347621153);
}

export function OpenExternalURL(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(2087603154, rawURL);
}

export function OpenExternalUrl(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(1545599634, rawURL);
}

export function OpenUserDataPath(): $CancellablePromise<void> {
    return $Call.ByID(1145954766);
}

export function PreviewConfig(): $CancellablePromise<$models.ConfigPreview> {
    return $Call.ByID(4266092968).then(($result: any) => {
        return $$createType56($result);
    });
}

export function PreviewConfigDiff(): $CancellablePromise<$models.ConfigPreview> {
    return $Call.ByID(903682911).then(($result: any) => {
        return $$createType56($result);
    });
}

export function ReadCoreLog(options: $models.LogReadOptions): $CancellablePromise<$models.LogReadResult> {
    return $Call.ByID(573688873, options).then(($result: any) => {
        return $$createType67($result);
    });
}

export function ReadLog(options: $models.LogReadOptions): $CancellablePromise<$models.LogReadResult> {
    return $Call.ByID(1118261216, options).then(($result: any) => {
        return $$createType67($result);
    });
}

export function RefreshAllRuleSets(): $CancellablePromise<void> {
    return $Call.ByID(3324919439);
}

export function RefreshProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(326033034, id);
}

export function RefreshProfileProvider(profileID: string, providerName: string): $CancellablePromise<void> {
    return $Call.ByID(712333415, profileID, providerName);
}

export function RefreshProfileProviders(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(3938035580, profileID);
}

export function RefreshRuleSet(id: string): $CancellablePromise<void> {
    return $Call.ByID(4050742981, id);
}

export function ReorderDNSPolicies(orderedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(2487416746, orderedIDs);
}

export function ReorderDNSServers(orderedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(3656011832, orderedIDs);
}

export function ReorderPolicies(orderedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(3206462363, orderedIDs);
}

export function ReorderProfiles(orderedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(4027156467, orderedIDs);
}

export function ReorderRuleSets(orderedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(2528680250, orderedIDs);
}

export function Restart(): $CancellablePromise<boolean> {
    return $Call.ByID(1691151109);
}

export function RestartCore(): $CancellablePromise<void> {
    return $Call.ByID(780095710);
}

export function RunLauncherTaskNow(): $CancellablePromise<$models.LauncherTaskResult> {
    return $Call.ByID(46071274).then(($result: any) => {
        return $$createType66($result);
    });
}

export function RunScheduledRefresh(): $CancellablePromise<void> {
    return $Call.ByID(2585729313);
}

export function SaveDNSPolicy(policy: $models.DNSPolicy): $CancellablePromise<$models.DNSPolicy> {
    return $Call.ByID(1222208764, policy).then(($result: any) => {
        return $$createType24($result);
    });
}

export function SaveDNSServer(server: $models.DNSServer): $CancellablePromise<$models.DNSServer> {
    return $Call.ByID(3777513741, server).then(($result: any) => {
        return $$createType28($result);
    });
}

export function SavePoliciesBatch(policies: $models.Policy[], clearFirst: boolean): $CancellablePromise<number> {
    return $Call.ByID(162091251, policies, clearFirst);
}

export function SavePolicy(policy: $models.Policy): $CancellablePromise<$models.Policy> {
    return $Call.ByID(1091925409, policy).then(($result: any) => {
        return $$createType38($result);
    });
}

export function SaveProfile(profile: $models.Profile): $CancellablePromise<$models.Profile> {
    return $Call.ByID(3874521152, profile).then(($result: any) => {
        return $$createType49($result);
    });
}

export function SaveRuleProvider(ruleSet: $models.RuleSet): $CancellablePromise<void> {
    return $Call.ByID(589176088, ruleSet);
}

export function SaveRuleSet(ruleSet: $models.RuleSet): $CancellablePromise<$models.RuleSet> {
    return $Call.ByID(422456983, ruleSet).then(($result: any) => {
        return $$createType40($result);
    });
}

export function SaveSettings(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(2168688002, settings);
}

export function SelectProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(4066368183, id);
}

export function SelectProxy(group: string, proxy: string): $CancellablePromise<void> {
    return $Call.ByID(2568039446, group, proxy);
}

export function SetAutoLaunch(enable: boolean): $CancellablePromise<void> {
    return $Call.ByID(3255808974, enable);
}

export function SetPolicyFinalOutbound(value: string): $CancellablePromise<void> {
    return $Call.ByID(3471278168, value);
}

export function SetPreference(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2159534099, key, value);
}

export function SetProfileCustomGroups(profileID: string, groups: $models.CustomProxyGroup[]): $CancellablePromise<void> {
    return $Call.ByID(2739324500, profileID, groups);
}

export function SetProfileDNSPolicyOverride(profileID: string, policyID: string, server: string): $CancellablePromise<void> {
    return $Call.ByID(1058709124, profileID, policyID, server);
}

export function SetProfileDNSServerDetour(profileID: string, serverID: string, detour: string): $CancellablePromise<void> {
    return $Call.ByID(3126939796, profileID, serverID, detour);
}

export function SetProfileDnsPolicy(profileID: string, dnsPolicyID: string, dnsServerID: string): $CancellablePromise<void> {
    return $Call.ByID(3004566204, profileID, dnsPolicyID, dnsServerID);
}

export function SetProfileDnsServerDetour(profileID: string, dnsServerID: string, detour: string): $CancellablePromise<void> {
    return $Call.ByID(1854633428, profileID, dnsServerID, detour);
}

export function SetProfilePolicy(profileID: string, policyID: string, preferredOutbounds: string[]): $CancellablePromise<void> {
    return $Call.ByID(4123234337, profileID, policyID, preferredOutbounds);
}

export function SetProfilePolicyOverride(profileID: string, policyID: string, outbound: string): $CancellablePromise<void> {
    return $Call.ByID(898296977, profileID, policyID, outbound);
}

export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3097897662, key, value);
}

export function SetSystemProxy(enable: boolean): $CancellablePromise<void> {
    return $Call.ByID(3354626933, enable);
}

export function SortProfileNodesByLatency(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(2221537261, profileID);
}

export function Start(): $CancellablePromise<boolean> {
    return $Call.ByID(1503116314);
}

export function StartCore(): $CancellablePromise<void> {
    return $Call.ByID(2847485405);
}

export function StartCoreService(): $CancellablePromise<void> {
    return $Call.ByID(3040368252);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2428295546);
}

export function StopCore(): $CancellablePromise<void> {
    return $Call.ByID(4051658493);
}

export function StopCoreService(): $CancellablePromise<void> {
    return $Call.ByID(3035823068);
}

export function TestClashAPI(): $CancellablePromise<$models.ClashProbe> {
    return $Call.ByID(701789277).then(($result: any) => {
        return $$createType68($result);
    });
}

export function TestDNSServer(id: string): $CancellablePromise<$models.ProbeItem> {
    return $Call.ByID(827173362, id).then(($result: any) => {
        return $$createType69($result);
    });
}

export function TestProfileNodes(profileID: string, testURL: string, timeout: number): $CancellablePromise<$models.ProbeItem[]> {
    return $Call.ByID(2001171972, profileID, testURL, timeout).then(($result: any) => {
        return $$createType70($result);
    });
}

export function TestProfileProvider(profileID: string, providerName: string, timeout: number): $CancellablePromise<$models.ProbeItem[]> {
    return $Call.ByID(996340014, profileID, providerName, timeout).then(($result: any) => {
        return $$createType70($result);
    });
}

export function TestProxyDelay(name: string): $CancellablePromise<number> {
    return $Call.ByID(2209596689, name);
}

export function ToggleDNSServerEnabled(id: string, enabled: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(2306601543, id, enabled);
}

export function ToggleDnsServerEnabled(id: string, enabled: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(1804329159, id, enabled);
}

export function Uninstall(): $CancellablePromise<$models.LauncherTaskResult> {
    return $Call.ByID(1515462740).then(($result: any) => {
        return $$createType66($result);
    });
}

export function UninstallCoreService(): $CancellablePromise<void> {
    return $Call.ByID(2925683142);
}

export function UninstallLauncherTask(): $CancellablePromise<$models.LauncherTaskResult> {
    return $Call.ByID(2957462353).then(($result: any) => {
        return $$createType66($result);
    });
}

export function UpdateDnsPoliciesOrder(orders: $models.OrderItem[]): $CancellablePromise<void> {
    return $Call.ByID(244127052, orders);
}

export function UpdateDnsPolicy(id: string, updates: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(1075720544, id, updates);
}

export function UpdateDnsServer(id: string, updates: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(2965361753, id, updates);
}

export function UpdateDnsServersOrder(orderedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(1787538198, orderedIDs);
}

export function UpdatePoliciesOrder(orders: $models.OrderItem[]): $CancellablePromise<void> {
    return $Call.ByID(2642251779, orders);
}

export function UpdatePolicy(id: string, updates: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(1533836477, id, updates);
}

export function UpdateProfile(profileID: string): $CancellablePromise<string> {
    return $Call.ByID(3471270404, profileID);
}

export function UpdateProfileContent(profileID: string, content: string): $CancellablePromise<$models.Profile> {
    return $Call.ByID(365958577, profileID, content).then(($result: any) => {
        return $$createType49($result);
    });
}

export function UpdateProfileCustomGroup(profileID: string, groupName: string, updates: $models.CustomProxyGroup): $CancellablePromise<void> {
    return $Call.ByID(3538961766, profileID, groupName, updates);
}

export function UpdateProfileCustomGroupsOrder(profileID: string, orders: $models.CustomProxyGroupOrder[]): $CancellablePromise<void> {
    return $Call.ByID(3759113633, profileID, orders);
}

export function UpdateProfileDetails(id: string, name: string, profileURL: string, updateInterval: number): $CancellablePromise<void> {
    return $Call.ByID(690522866, id, name, profileURL, updateInterval);
}

export function UpdateProfileGroup(profileID: string, index: number, group: $models.ProxyGroupConfig): $CancellablePromise<$models.ProxyGroupConfig> {
    return $Call.ByID(3269837879, profileID, index, group).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateProfileInterval(id: string, updateInterval: number): $CancellablePromise<void> {
    return $Call.ByID(3036322117, id, updateInterval);
}

export function UpdateProfileNode(profileID: string, index: number, node: $models.ProxyNode): $CancellablePromise<$models.ProxyNode> {
    return $Call.ByID(1573217152, profileID, index, node).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateProfilesOrder(orderedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(2759712295, orderedIDs);
}

export function UpdateRuleProvider(id: string, updates: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(1119139420, id, updates);
}

export function UpdateRuleProvidersOrder(orderedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(1976866959, orderedIDs);
}

export function UpdateTrayMenu(): $CancellablePromise<void> {
    return $Call.ByID(2815863176);
}

export function ValidateConfig(): $CancellablePromise<$models.CoreCheckResult> {
    return $Call.ByID(2208100874).then(($result: any) => {
        return $$createType71($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProxyNode.createFrom;
const $$createType1 = $models.ProxyGroupConfig.createFrom;
const $$createType2 = $models.PresetApplyResult.createFrom;
const $$createType3 = $models.UpdateCheckResult.createFrom;
const $$createType4 = $models.ClearOperationResult.createFrom;
const $$createType5 = $models.RuleProviderDownloadResult.createFrom;
const $$createType6 = $models.ConfigOperationResult.createFrom;
const $$createType7 = $models.IPInfo.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = $models.RoverProfileDNSServerItem.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.RuleSetGroup.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Map($Create.Any, $Create.Any);
const $$createType15 = $models.AvailableOutbound.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.BuildInfo.createFrom;
const $$createType18 = $models.BuiltinTemplate.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.Connection.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $models.CoreServiceStatus.createFrom;
const $$createType23 = $Create.Array($$createType9);
const $$createType24 = $models.DNSPolicy.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = $models.DNSServerRef.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = $models.DNSServer.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = $models.DNSRuntimeStatus.createFrom;
const $$createType31 = $models.DashboardState.createFrom;
const $$createType32 = $models.DatabaseStatus.createFrom;
const $$createType33 = $models.InitialLogLineCount.createFrom;
const $$createType34 = $Create.Array($Create.Any);
const $$createType35 = $models.LogEntry.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = $models.PlatformStatus.createFrom;
const $$createType38 = $models.Policy.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = $models.RuleSet.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = $models.CustomProxyGroup.createFrom;
const $$createType43 = $Create.Array($$createType42);
const $$createType44 = $models.RoverProfileDNSPolicyItem.createFrom;
const $$createType45 = $Create.Nullable($$createType44);
const $$createType46 = $Create.Array($$createType0);
const $$createType47 = $models.RoverProfilePolicyItem.createFrom;
const $$createType48 = $Create.Nullable($$createType47);
const $$createType49 = $models.Profile.createFrom;
const $$createType50 = $Create.Array($$createType49);
const $$createType51 = $models.ProxyGroup.createFrom;
const $$createType52 = $Create.Array($$createType51);
const $$createType53 = $models.RefreshScheduleItem.createFrom;
const $$createType54 = $Create.Array($$createType53);
const $$createType55 = $models.RuleProviderViewContent.createFrom;
const $$createType56 = $models.ConfigPreview.createFrom;
const $$createType57 = $models.SelectedProfileState.createFrom;
const $$createType58 = $models.Settings.createFrom;
const $$createType59 = $models.SingBoxRuntimeStatus.createFrom;
const $$createType60 = $models.TemplatePolicyPayload.createFrom;
const $$createType61 = $models.TemplateSummary.createFrom;
const $$createType62 = $Create.Array($$createType61);
const $$createType63 = $models.TrafficState.createFrom;
const $$createType64 = $models.ConfigImportResult.createFrom;
const $$createType65 = $models.TemplateImportResult.createFrom;
const $$createType66 = $models.LauncherTaskResult.createFrom;
const $$createType67 = $models.LogReadResult.createFrom;
const $$createType68 = $models.ClashProbe.createFrom;
const $$createType69 = $models.ProbeItem.createFrom;
const $$createType70 = $Create.Array($$createType69);
const $$createType71 = $models.CoreCheckResult.createFrom;
